### PR TITLE
Add `HasCharacterLimit` Trait and Update README

### PR DESCRIPTION
**Pull request by edeoliv**
## Summary

This pull request introduces the `HasCharacterLimit` trait and updates the README documentation to reflect this new feature.

## Changes
- Added `HasCharacterLimit` trait to the `LaraZeus\Quantity\Traits` component.
- Updated the README with instructions on how to use the `characterLimit` method.

## Usage
To set a character limit on the `amount_number` field, use the `characterLimit` method as shown below:

```php
\LaraZeus\Quantity\Components\Quantity::make('amount_number')
    ->heading('Select Quantity')
    ->default(3)
    ->maxValue(10)
    ->minValue(2)
    ->characterLimit(2) // Add this line to set the character limit
    ->stacked();

### CODE REVIEW

**Comment by edeoliv** [comment]
I forgot to modify the view, as soon as I modify it to show the characters I reopen the PR

**Comment by atmonshi** [comment]
thank you so much for your contribution.

but I am just confused, what the different between the new method: `characterLimit` and the existing one: `maxValue` and `maxValue` ?

the use for quantity is for numbers only. and you can set the max and min value.

**Comment by atmonshi** [comment]
and the same for: `CanBeShownInsideControl` vs `stacked`! :)

**Comment by edeoliv** [comment]
Basically what it does is to display the number of allowed characters and as the field is filled in it updates the number of allowed characters. So it is different from what you already have in the plugin.

imagen

**Comment by atmonshi** [comment]
so it show the allowed length of the input, you could use `strlen` or something similar for that and display it as a hint text or help text, so no need for a new method that can get others confusing too.

in you example form the screenshot the `strlen` will be 2 if you set your max value to 99.

**Comment by edeoliv** [comment]
Well for me it works with the addition of the new method and I take advantage of it in a general way in the whole project without strlen and similar, but well respect your decision in the end is your plugin your rules. 
Sorry for the inconvenience

**Pull request closed without merging**
